### ISSUE TITLE
onbuild: '/entrypoint.sh' could not be invoked.

### ISSUE THREAD

**Issue by jujes** [Dragontek/octobercms#1]
**docker-compose version 1.7.1, build 0a9ab35
Docker version 1.11.2, build b9f10c9**

```
ERROR: for october  Container command '/entrypoint.sh' could not be invoked.
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "compose/cli/main.py", line 63, in main
AttributeError: 'ProjectError' object has no attribute 'msg'
docker-compose returned -1
```

my docker-compose.yml:

```
postgres:
  image: postgres
  environment:
    - MYSQL_ROOT_PASSWORD=example

october:
  image: demo/octobercms
  links:
    - postgres:postgres
  container_name: octobercms.top
  environment:
    - VIRTUAL_HOST=octobercms.top
```

**Comment by jmondragon** [comment]
Thank you, I am looking into it.

**Comment by jujes** [comment]
_half-solved..._ **docker-entrypoint.sh need chmod +x** before build, in my case:

```
cd .../onbuild
chmod +x docker-entrypoint.sh

```
and **change** the end of **Dockerfile**:

```
COPY ./docker-entrypoint.sh /

ENTRYPOINT ["/docker-entrypoint.sh"]
```

**_the new issue:_** looking docker logs: "/docker-entrypoint.s"   

```
OctoberCMS not found in /var/www/html - copying now...
Complete! OctoberCMS has been successfully copied to /var/www/html
Could not open input file: artisan
```

my new docker-compose.yml:

```
october:
  image: demo/octobercms
  links:
    - db:mysql
  container_name: octobercms.top
  environment:
    - OCTOBER_DB_DRIVER=mysql
    - OCTOBER_DB_PASSWORD=admin
    - OCTOBER_DB_USER=jujes
    - VIRTUAL_HOST=octobercms.top

db:
  image: mysql
  environment:
    MYSQL_ROOT_PASSWORD: example
  container_name: octobercms.db
```
