### ISSUE TITLE
System UID in volume permissions

### ISSUE THREAD

**Issue by czerwonyd** [Dragontek/octobercms#10]
Hi,
When using the container on Linux machine there is a problem with permissions in shared volume. It is a docker wide problem, but I do not want to create fork of your project just to add one RUN in my DockerFile.
The problem is that all files in share are owned by user www-data, which default UID is 33. So if your local user has a different UID (which is true in almost all cases), than the user cannot edit files in share.

Possible solution:
I have found a funny solution for the case that is not very elegant, but works and does not mess with a container configuration and working with it.
There could be one more environment variable, let's say `$WWW_DATA_UID` which by default is set to 33 and at the end of the entrypoint script it will run `usermod -u $WWW_DATA_UID www-data`.
This way if I define the variable in my case as 1000 (my UID) then it will become possible for me to edit files in share.

What do you think about it? Or maybe I got something wrong, because I am new to docker.

**Comment by czerwonyd** [comment]
I have decided to create my own docker container. The only problem is that Docker Hub guys do not worry about all those people who have not received activation e-mail which I am one of (and there are plenty of them!).
If you want to see the effect take a look at https://github.com/initbizlab/octobercms-docker
Maybe there will not be a need to use my container if yours will do everything, but the case with UID tipped the balance.

**Comment by jmondragon** [comment]
I didn't include everything that you have in your image, but I do allow you to specify a user.  Also, upstream added `APACHE_RUN_USER` and `APACHE_RUN_GROUP`.

If you run it like this:
```
docker run -p 8080:80 -v ${PWD}:/var/www/html -u 1000:1000 --sysctl net.ipv4.ip_unprivileged_port_start=0 -d dragontek/octobercms
```
Where 1000 is your user id, it will have the correct user permissions to be able to modify the files.

**Comment by vephinx** [comment]
My `docker-compose.yml` file is as follows:

```
version: '3'
services:
  web:
    container_name: octobercms_test
    image: "dragontek/octobercms"
    expose:
      - "80"
    user: 1000:1000
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0
    restart: unless-stopped
    networks:
      - web
      - internal
    volumes:
      - ./data:/var/www/html
    environment:
      - OCTOBER_APP_URL=https://DOMAIN.com
      - OCTOBER_CMS_LINK_POLICY=secure
      - OCTOBER_CMS_ACTIVE_THEME=demo
      - APACHE_RUN_USER=1000
      - APACHE_RUN_GROUP=1000
    labels:
      - "traefik.backend=octobertest"
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:DOMAIN.com"
      - "traefik.port=80"

  mysql:
    container_name: octobercms_mysql_test
    image: "mariadb"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=october
    networks:
      - internal

networks:
  internal:    
  web:
    external: true
```

However, the `data` folder is created as root and not as user 1000. What am I doing wrong?
