### ISSUE TITLE
The stream or file "/var/www/html/storage/logs/system.log" could not be opened: failed to open stream: Permission denied

### ISSUE THREAD

**Issue by sebastian-ruiz** [Dragontek/octobercms#13]
I get the error: `The stream or file "/var/www/html/storage/logs/system.log" could not be opened: failed to open stream: Permission denied`. 
See below for the `docker-compose.yml` I am using.
I am not mounting `/var/www/html/storage/` and I get the aforementioned error.

```
version: '3'
services:
  web:
    image: dragontek/octobercms:latest
    expose:
      - "80"
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0
    restart: unless-stopped
    networks:
      - web
      - internal
    depends_on:
      - mysql
    environment:
      - OCTOBER_APP_URL=https://october.DOMAIN.COM
      - OCTOBER_CMS_LINK_POLICY=secure
      - OCTOBER_DB_DRIVER=mysql
      - OCTOBER_DB_HOST=mysql
      - OCTOBER_DB_PORT=3306
      - OCTOBER_DB_USER=root
      - OCTOBER_DB_PASSWORD=october
      - OCTOBER_DB_NAME=october_cms
      - OCTOBER_CMS_DISABLE_CORE_UPDATES=true
    labels:
      - "traefik.backend=october"
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:october.DOMAIN.COM"
      - "traefik.port=80"

  mysql:
    image: mariadb:latest
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=october
    networks:
      - internal

networks:
  internal:    
  web:
    external: true

```
